version: "3.8"

services:
  linkedin-scraper:
    build: .
    container_name: linkedin-scraper-api
    ports:
      - "8080:8080"
    volumes:
      - ./accounts.json:/app/accounts.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
